replicaCount: 2

image:
  repository: "hareeshn903/atoz-app"
  tag: "${IMAGE_TAG}"

serviceAccount:
  create: true

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx

  host: siri.local

resources:
  requests:
    cpu: 250m
    memory: 512Mi

  limits:
    cpu: 500m
    memory: 1Gi

container:
  port: 8080

postgres:

  image: postgres:16

  database: accountdb

  username: postgres

  password: password

  storage: 2Gi

  servicePort: 5432
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  cpuUtilization: 70

app:
  profile: dev

podAnnotations: {}

nodeSelector: {}

tolerations: []

affinity: {}