apiVersion: apps/v1

kind: Deployment

metadata:
  name: {{ include "mini-account-management.fullname" . }}

spec:
  replicas: {{ .Values.replicaCount }}
  
  selector:
    matchLabels:
      app: mini-account-management

  template:

    metadata:
      labels:
        app: mini-account-management

    spec:

      serviceAccountName: {{ include "mini-account-management.fullname" . }}-sa

      containers:

        - name: mini-account-management

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          ports:
            - containerPort: 8080

          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: SPRING_PROFILES_ACTIVE

            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/{{ .Values.postgres.database }}

            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.postgres.username }}

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}

            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5