apiVersion: v1

kind: Service

metadata:
  name: {{ include "mini-account-management.fullname" . }}

spec:
  type: {{ .Values.service.type }}

  selector:
    app: mini-account-management

  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080