apiVersion: v1

kind: Service

metadata:
  name: mini-account-management

spec:
  type: {{ .Values.service.type }}

  selector:
    app: mini-account-management

  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080